// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package com.lindec.netty.fileMessage.protobuf;

public final class DbEvent {
  private DbEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.lindec.netty.fileMessage.protobuf.Event}
   */
  public enum Event
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MESSAGE_TYPE_SECURE_MODEL = 0;</code>
     */
    MESSAGE_TYPE_SECURE_MODEL(0),
    /**
     * <code>MESSAGE_TYPE_REQUEST_FILE = 1;</code>
     */
    MESSAGE_TYPE_REQUEST_FILE(1),
    /**
     * <code>MESSAGE_TYPE_RESPONSE_FILE = 2;</code>
     */
    MESSAGE_TYPE_RESPONSE_FILE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MESSAGE_TYPE_SECURE_MODEL = 0;</code>
     */
    public static final int MESSAGE_TYPE_SECURE_MODEL_VALUE = 0;
    /**
     * <code>MESSAGE_TYPE_REQUEST_FILE = 1;</code>
     */
    public static final int MESSAGE_TYPE_REQUEST_FILE_VALUE = 1;
    /**
     * <code>MESSAGE_TYPE_RESPONSE_FILE = 2;</code>
     */
    public static final int MESSAGE_TYPE_RESPONSE_FILE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Event valueOf(int value) {
      return forNumber(value);
    }

    public static Event forNumber(int value) {
      switch (value) {
        case 0: return MESSAGE_TYPE_SECURE_MODEL;
        case 1: return MESSAGE_TYPE_REQUEST_FILE;
        case 2: return MESSAGE_TYPE_RESPONSE_FILE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Event>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Event> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Event>() {
            public Event findValueByNumber(int number) {
              return Event.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return DbEvent.getDescriptor().getEnumTypes().get(0);
    }

    private static final Event[] VALUES = values();

    public static Event valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Event(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.lindec.netty.fileMessage.protobuf.Event)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Event.proto\022%com.lindec.netty.fileMess" +
      "age.protobuf*e\n\005Event\022\035\n\031MESSAGE_TYPE_SE" +
      "CURE_MODEL\020\000\022\035\n\031MESSAGE_TYPE_REQUEST_FIL" +
      "E\020\001\022\036\n\032MESSAGE_TYPE_RESPONSE_FILE\020\002B\tB\007D" +
      "bEventb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
