// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package com.lindec.netty.fileMessage.protobuf;

public final class DbRequestModel {
  private DbRequestModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lindec.netty.fileMessage.protobuf.RequestModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string file_name = 1;</code>
     */
    String getFileName();
    /**
     * <code>string file_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>int64 starPos = 2;</code>
     */
    long getStarPos();

    /**
     * <code>bytes bytes = 3;</code>
     */
    com.google.protobuf.ByteString getBytes();

    /**
     * <code>int32 endPos = 4;</code>
     */
    int getEndPos();

    /**
     * <code>string file_type = 5;</code>
     */
    String getFileType();
    /**
     * <code>string file_type = 5;</code>
     */
    com.google.protobuf.ByteString
        getFileTypeBytes();

    /**
     * <code>int64 file_size = 6;</code>
     */
    long getFileSize();
  }
  /**
   * Protobuf type {@code com.lindec.netty.fileMessage.protobuf.RequestModel}
   */
  public  static final class RequestModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lindec.netty.fileMessage.protobuf.RequestModel)
      RequestModelOrBuilder {
    // Use RequestModel.newBuilder() to construct.
    private RequestModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestModel() {
      fileName_ = "";
      starPos_ = 0L;
      bytes_ = com.google.protobuf.ByteString.EMPTY;
      endPos_ = 0;
      fileType_ = "";
      fileSize_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 16: {

              starPos_ = input.readInt64();
              break;
            }
            case 26: {

              bytes_ = input.readBytes();
              break;
            }
            case 32: {

              endPos_ = input.readInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              fileType_ = s;
              break;
            }
            case 48: {

              fileSize_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DbRequestModel.internal_static_com_lindec_netty_fileMessage_protobuf_RequestModel_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DbRequestModel.internal_static_com_lindec_netty_fileMessage_protobuf_RequestModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestModel.class, Builder.class);
    }

    public static final int FILE_NAME_FIELD_NUMBER = 1;
    private volatile Object fileName_;
    /**
     * <code>string file_name = 1;</code>
     */
    public String getFileName() {
      Object ref = fileName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string file_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARPOS_FIELD_NUMBER = 2;
    private long starPos_;
    /**
     * <code>int64 starPos = 2;</code>
     */
    public long getStarPos() {
      return starPos_;
    }

    public static final int BYTES_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString bytes_;
    /**
     * <code>bytes bytes = 3;</code>
     */
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }

    public static final int ENDPOS_FIELD_NUMBER = 4;
    private int endPos_;
    /**
     * <code>int32 endPos = 4;</code>
     */
    public int getEndPos() {
      return endPos_;
    }

    public static final int FILE_TYPE_FIELD_NUMBER = 5;
    private volatile Object fileType_;
    /**
     * <code>string file_type = 5;</code>
     */
    public String getFileType() {
      Object ref = fileType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileType_ = s;
        return s;
      }
    }
    /**
     * <code>string file_type = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFileTypeBytes() {
      Object ref = fileType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_SIZE_FIELD_NUMBER = 6;
    private long fileSize_;
    /**
     * <code>int64 file_size = 6;</code>
     */
    public long getFileSize() {
      return fileSize_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
      }
      if (starPos_ != 0L) {
        output.writeInt64(2, starPos_);
      }
      if (!bytes_.isEmpty()) {
        output.writeBytes(3, bytes_);
      }
      if (endPos_ != 0) {
        output.writeInt32(4, endPos_);
      }
      if (!getFileTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, fileType_);
      }
      if (fileSize_ != 0L) {
        output.writeInt64(6, fileSize_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
      }
      if (starPos_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, starPos_);
      }
      if (!bytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, bytes_);
      }
      if (endPos_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, endPos_);
      }
      if (!getFileTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, fileType_);
      }
      if (fileSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, fileSize_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RequestModel)) {
        return super.equals(obj);
      }
      RequestModel other = (RequestModel) obj;

      boolean result = true;
      result = result && getFileName()
          .equals(other.getFileName());
      result = result && (getStarPos()
          == other.getStarPos());
      result = result && getBytes()
          .equals(other.getBytes());
      result = result && (getEndPos()
          == other.getEndPos());
      result = result && getFileType()
          .equals(other.getFileType());
      result = result && (getFileSize()
          == other.getFileSize());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + STARPOS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStarPos());
      hash = (37 * hash) + BYTES_FIELD_NUMBER;
      hash = (53 * hash) + getBytes().hashCode();
      hash = (37 * hash) + ENDPOS_FIELD_NUMBER;
      hash = (53 * hash) + getEndPos();
      hash = (37 * hash) + FILE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getFileType().hashCode();
      hash = (37 * hash) + FILE_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFileSize());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RequestModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RequestModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RequestModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lindec.netty.fileMessage.protobuf.RequestModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lindec.netty.fileMessage.protobuf.RequestModel)
        RequestModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DbRequestModel.internal_static_com_lindec_netty_fileMessage_protobuf_RequestModel_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DbRequestModel.internal_static_com_lindec_netty_fileMessage_protobuf_RequestModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestModel.class, Builder.class);
      }

      // Construct using com.lindec.netty.fileMessage.protobuf.DbRequestModel.RequestModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        fileName_ = "";

        starPos_ = 0L;

        bytes_ = com.google.protobuf.ByteString.EMPTY;

        endPos_ = 0;

        fileType_ = "";

        fileSize_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DbRequestModel.internal_static_com_lindec_netty_fileMessage_protobuf_RequestModel_descriptor;
      }

      public RequestModel getDefaultInstanceForType() {
        return RequestModel.getDefaultInstance();
      }

      public RequestModel build() {
        RequestModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RequestModel buildPartial() {
        RequestModel result = new RequestModel(this);
        result.fileName_ = fileName_;
        result.starPos_ = starPos_;
        result.bytes_ = bytes_;
        result.endPos_ = endPos_;
        result.fileType_ = fileType_;
        result.fileSize_ = fileSize_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestModel) {
          return mergeFrom((RequestModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestModel other) {
        if (other == RequestModel.getDefaultInstance()) return this;
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.getStarPos() != 0L) {
          setStarPos(other.getStarPos());
        }
        if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
          setBytes(other.getBytes());
        }
        if (other.getEndPos() != 0) {
          setEndPos(other.getEndPos());
        }
        if (!other.getFileType().isEmpty()) {
          fileType_ = other.fileType_;
          onChanged();
        }
        if (other.getFileSize() != 0L) {
          setFileSize(other.getFileSize());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object fileName_ = "";
      /**
       * <code>string file_name = 1;</code>
       */
      public String getFileName() {
        Object ref = fileName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string file_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string file_name = 1;</code>
       */
      public Builder setFileName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string file_name = 1;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string file_name = 1;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private long starPos_ ;
      /**
       * <code>int64 starPos = 2;</code>
       */
      public long getStarPos() {
        return starPos_;
      }
      /**
       * <code>int64 starPos = 2;</code>
       */
      public Builder setStarPos(long value) {
        
        starPos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 starPos = 2;</code>
       */
      public Builder clearStarPos() {
        
        starPos_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bytes = 3;</code>
       */
      public com.google.protobuf.ByteString getBytes() {
        return bytes_;
      }
      /**
       * <code>bytes bytes = 3;</code>
       */
      public Builder setBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bytes = 3;</code>
       */
      public Builder clearBytes() {
        
        bytes_ = getDefaultInstance().getBytes();
        onChanged();
        return this;
      }

      private int endPos_ ;
      /**
       * <code>int32 endPos = 4;</code>
       */
      public int getEndPos() {
        return endPos_;
      }
      /**
       * <code>int32 endPos = 4;</code>
       */
      public Builder setEndPos(int value) {
        
        endPos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 endPos = 4;</code>
       */
      public Builder clearEndPos() {
        
        endPos_ = 0;
        onChanged();
        return this;
      }

      private Object fileType_ = "";
      /**
       * <code>string file_type = 5;</code>
       */
      public String getFileType() {
        Object ref = fileType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fileType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string file_type = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFileTypeBytes() {
        Object ref = fileType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fileType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string file_type = 5;</code>
       */
      public Builder setFileType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string file_type = 5;</code>
       */
      public Builder clearFileType() {
        
        fileType_ = getDefaultInstance().getFileType();
        onChanged();
        return this;
      }
      /**
       * <code>string file_type = 5;</code>
       */
      public Builder setFileTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileType_ = value;
        onChanged();
        return this;
      }

      private long fileSize_ ;
      /**
       * <code>int64 file_size = 6;</code>
       */
      public long getFileSize() {
        return fileSize_;
      }
      /**
       * <code>int64 file_size = 6;</code>
       */
      public Builder setFileSize(long value) {
        
        fileSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 file_size = 6;</code>
       */
      public Builder clearFileSize() {
        
        fileSize_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.lindec.netty.fileMessage.protobuf.RequestModel)
    }

    // @@protoc_insertion_point(class_scope:com.lindec.netty.fileMessage.protobuf.RequestModel)
    private static final RequestModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RequestModel();
    }

    public static RequestModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestModel>
        PARSER = new com.google.protobuf.AbstractParser<RequestModel>() {
      public RequestModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestModel> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RequestModel> getParserForType() {
      return PARSER;
    }

    public RequestModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lindec_netty_fileMessage_protobuf_RequestModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lindec_netty_fileMessage_protobuf_RequestModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rRequest.proto\022%com.lindec.netty.fileMe" +
      "ssage.protobuf\"w\n\014RequestModel\022\021\n\tfile_n" +
      "ame\030\001 \001(\t\022\017\n\007starPos\030\002 \001(\003\022\r\n\005bytes\030\003 \001(" +
      "\014\022\016\n\006endPos\030\004 \001(\005\022\021\n\tfile_type\030\005 \001(\t\022\021\n\t" +
      "file_size\030\006 \001(\003B\020B\016DbRequestModelb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lindec_netty_fileMessage_protobuf_RequestModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lindec_netty_fileMessage_protobuf_RequestModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lindec_netty_fileMessage_protobuf_RequestModel_descriptor,
        new String[] { "FileName", "StarPos", "Bytes", "EndPos", "FileType", "FileSize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
