// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package com.lindec.netty.fileMessage.protobuf;

public final class DbResponseModel {
  private DbResponseModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lindec.netty.fileMessage.protobuf.ResponseModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 start = 1;</code>
     */
    long getStart();

    /**
     * <code>string file_name = 2;</code>
     */
    String getFileName();
    /**
     * <code>string file_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>string file_url = 3;</code>
     */
    String getFileUrl();
    /**
     * <code>string file_url = 3;</code>
     */
    com.google.protobuf.ByteString
        getFileUrlBytes();

    /**
     * <code>bool end = 4;</code>
     */
    boolean getEnd();

    /**
     * <code>int32 progress = 5;</code>
     */
    int getProgress();
  }
  /**
   * Protobuf type {@code com.lindec.netty.fileMessage.protobuf.ResponseModel}
   */
  public  static final class ResponseModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lindec.netty.fileMessage.protobuf.ResponseModel)
      ResponseModelOrBuilder {
    // Use ResponseModel.newBuilder() to construct.
    private ResponseModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseModel() {
      start_ = 0L;
      fileName_ = "";
      fileUrl_ = "";
      end_ = false;
      progress_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              start_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              fileUrl_ = s;
              break;
            }
            case 32: {

              end_ = input.readBool();
              break;
            }
            case 40: {

              progress_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DbResponseModel.internal_static_com_lindec_netty_fileMessage_protobuf_ResponseModel_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DbResponseModel.internal_static_com_lindec_netty_fileMessage_protobuf_ResponseModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResponseModel.class, Builder.class);
    }

    public static final int START_FIELD_NUMBER = 1;
    private long start_;
    /**
     * <code>int64 start = 1;</code>
     */
    public long getStart() {
      return start_;
    }

    public static final int FILE_NAME_FIELD_NUMBER = 2;
    private volatile Object fileName_;
    /**
     * <code>string file_name = 2;</code>
     */
    public String getFileName() {
      Object ref = fileName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string file_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_URL_FIELD_NUMBER = 3;
    private volatile Object fileUrl_;
    /**
     * <code>string file_url = 3;</code>
     */
    public String getFileUrl() {
      Object ref = fileUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string file_url = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFileUrlBytes() {
      Object ref = fileUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int END_FIELD_NUMBER = 4;
    private boolean end_;
    /**
     * <code>bool end = 4;</code>
     */
    public boolean getEnd() {
      return end_;
    }

    public static final int PROGRESS_FIELD_NUMBER = 5;
    private int progress_;
    /**
     * <code>int32 progress = 5;</code>
     */
    public int getProgress() {
      return progress_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (start_ != 0L) {
        output.writeInt64(1, start_);
      }
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileName_);
      }
      if (!getFileUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fileUrl_);
      }
      if (end_ != false) {
        output.writeBool(4, end_);
      }
      if (progress_ != 0) {
        output.writeInt32(5, progress_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (start_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, start_);
      }
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileName_);
      }
      if (!getFileUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fileUrl_);
      }
      if (end_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, end_);
      }
      if (progress_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, progress_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ResponseModel)) {
        return super.equals(obj);
      }
      ResponseModel other = (ResponseModel) obj;

      boolean result = true;
      result = result && (getStart()
          == other.getStart());
      result = result && getFileName()
          .equals(other.getFileName());
      result = result && getFileUrl()
          .equals(other.getFileUrl());
      result = result && (getEnd()
          == other.getEnd());
      result = result && (getProgress()
          == other.getProgress());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + START_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStart());
      hash = (37 * hash) + FILE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + FILE_URL_FIELD_NUMBER;
      hash = (53 * hash) + getFileUrl().hashCode();
      hash = (37 * hash) + END_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEnd());
      hash = (37 * hash) + PROGRESS_FIELD_NUMBER;
      hash = (53 * hash) + getProgress();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ResponseModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResponseModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResponseModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ResponseModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResponseModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResponseModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ResponseModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lindec.netty.fileMessage.protobuf.ResponseModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lindec.netty.fileMessage.protobuf.ResponseModel)
        ResponseModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DbResponseModel.internal_static_com_lindec_netty_fileMessage_protobuf_ResponseModel_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DbResponseModel.internal_static_com_lindec_netty_fileMessage_protobuf_ResponseModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResponseModel.class, Builder.class);
      }

      // Construct using com.lindec.netty.fileMessage.protobuf.DbResponseModel.ResponseModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        start_ = 0L;

        fileName_ = "";

        fileUrl_ = "";

        end_ = false;

        progress_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DbResponseModel.internal_static_com_lindec_netty_fileMessage_protobuf_ResponseModel_descriptor;
      }

      public ResponseModel getDefaultInstanceForType() {
        return ResponseModel.getDefaultInstance();
      }

      public ResponseModel build() {
        ResponseModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ResponseModel buildPartial() {
        ResponseModel result = new ResponseModel(this);
        result.start_ = start_;
        result.fileName_ = fileName_;
        result.fileUrl_ = fileUrl_;
        result.end_ = end_;
        result.progress_ = progress_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResponseModel) {
          return mergeFrom((ResponseModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResponseModel other) {
        if (other == ResponseModel.getDefaultInstance()) return this;
        if (other.getStart() != 0L) {
          setStart(other.getStart());
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (!other.getFileUrl().isEmpty()) {
          fileUrl_ = other.fileUrl_;
          onChanged();
        }
        if (other.getEnd() != false) {
          setEnd(other.getEnd());
        }
        if (other.getProgress() != 0) {
          setProgress(other.getProgress());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResponseModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResponseModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long start_ ;
      /**
       * <code>int64 start = 1;</code>
       */
      public long getStart() {
        return start_;
      }
      /**
       * <code>int64 start = 1;</code>
       */
      public Builder setStart(long value) {
        
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 start = 1;</code>
       */
      public Builder clearStart() {
        
        start_ = 0L;
        onChanged();
        return this;
      }

      private Object fileName_ = "";
      /**
       * <code>string file_name = 2;</code>
       */
      public String getFileName() {
        Object ref = fileName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string file_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string file_name = 2;</code>
       */
      public Builder setFileName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string file_name = 2;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string file_name = 2;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private Object fileUrl_ = "";
      /**
       * <code>string file_url = 3;</code>
       */
      public String getFileUrl() {
        Object ref = fileUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fileUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string file_url = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFileUrlBytes() {
        Object ref = fileUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fileUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string file_url = 3;</code>
       */
      public Builder setFileUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string file_url = 3;</code>
       */
      public Builder clearFileUrl() {
        
        fileUrl_ = getDefaultInstance().getFileUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string file_url = 3;</code>
       */
      public Builder setFileUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileUrl_ = value;
        onChanged();
        return this;
      }

      private boolean end_ ;
      /**
       * <code>bool end = 4;</code>
       */
      public boolean getEnd() {
        return end_;
      }
      /**
       * <code>bool end = 4;</code>
       */
      public Builder setEnd(boolean value) {
        
        end_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool end = 4;</code>
       */
      public Builder clearEnd() {
        
        end_ = false;
        onChanged();
        return this;
      }

      private int progress_ ;
      /**
       * <code>int32 progress = 5;</code>
       */
      public int getProgress() {
        return progress_;
      }
      /**
       * <code>int32 progress = 5;</code>
       */
      public Builder setProgress(int value) {
        
        progress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 progress = 5;</code>
       */
      public Builder clearProgress() {
        
        progress_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.lindec.netty.fileMessage.protobuf.ResponseModel)
    }

    // @@protoc_insertion_point(class_scope:com.lindec.netty.fileMessage.protobuf.ResponseModel)
    private static final ResponseModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResponseModel();
    }

    public static ResponseModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseModel>
        PARSER = new com.google.protobuf.AbstractParser<ResponseModel>() {
      public ResponseModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseModel> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ResponseModel> getParserForType() {
      return PARSER;
    }

    public ResponseModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lindec_netty_fileMessage_protobuf_ResponseModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lindec_netty_fileMessage_protobuf_ResponseModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Response.proto\022%com.lindec.netty.fileM" +
      "essage.protobuf\"b\n\rResponseModel\022\r\n\005star" +
      "t\030\001 \001(\003\022\021\n\tfile_name\030\002 \001(\t\022\020\n\010file_url\030\003" +
      " \001(\t\022\013\n\003end\030\004 \001(\010\022\020\n\010progress\030\005 \001(\005B\021B\017D" +
      "bResponseModelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lindec_netty_fileMessage_protobuf_ResponseModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lindec_netty_fileMessage_protobuf_ResponseModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lindec_netty_fileMessage_protobuf_ResponseModel_descriptor,
        new String[] { "Start", "FileName", "FileUrl", "End", "Progress", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
